-- Generated by Oracle SQL Developer Data Modeler 18.1.0.082.1035
--   at:        2018-04-28 08:38:30 CEST
--   site:      SQL Server 2012
--   type:      SQL Server 2012

CREATE TABLE komentar 
    ( idc INTEGER NOT NULL IDENTITY NOT FOR REPLICATION , 
     Predmet VARCHAR (20) NOT NULL , 
     Text VARCHAR (1000) NOT NULL , 
     Zakaznik_IDu INTEGER NOT NULL , 
     Zbozi_IDz INTEGER NOT NULL 
    )


ALTER TABLE Komentar ADD constraint komentar_pk PRIMARY KEY CLUSTERED (IDc)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )


CREATE TABLE kosik (
    zakaznik_idu   INTEGER NOT NULL,
    zbozi_idz      INTEGER NOT NULL,
    pocet          INTEGER NOT NULL
)


ALTER TABLE Kosik ADD constraint kosik_pk PRIMARY KEY CLUSTERED (Zakaznik_IDu, Zbozi_IDz)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )


CREATE TABLE objednavka 
    ( ido INTEGER NOT NULL IDENTITY NOT FOR REPLICATION , 
     Datum DATETIME NOT NULL , 
     Zakaznik_IDu INTEGER NOT NULL 
    )


ALTER TABLE Objednavka ADD constraint objednavka_pk PRIMARY KEY CLUSTERED (IDo)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )


CREATE TABLE obrazek 
    ( idob INTEGER NOT NULL IDENTITY NOT FOR REPLICATION , 
     Nazev VARCHAR (20) NOT NULL , 
     Zbozi_IDz INTEGER NOT NULL 
    )


ALTER TABLE Obrazek ADD constraint obrazek_pk PRIMARY KEY CLUSTERED (IDob)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )


CREATE TABLE obsahobjednavky (
    zbozi_idz        INTEGER NOT NULL,
    objednavka_ido   INTEGER NOT NULL,
    pocet            INTEGER NOT NULL
)


ALTER TABLE ObsahObjednavky ADD constraint obsahobjednavky_pk PRIMARY KEY CLUSTERED (Zbozi_IDz, Objednavka_IDo)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )


CREATE TABLE zakaznik 
    ( idu INTEGER NOT NULL IDENTITY NOT FOR REPLICATION , 
     Login VARCHAR (20) NOT NULL , 
     Email VARCHAR (30) NOT NULL , 
     Heslo VARCHAR (20) NOT NULL , 
     Krestni VARCHAR (20) NOT NULL , 
     Prijmeni VARCHAR (20) NOT NULL , 
     Ulice VARCHAR (20) NOT NULL , 
     Mesto VARCHAR (20) NOT NULL , 
     PSC VARCHAR (6) NOT NULL , 
     Tel VARCHAR (9) NOT NULL 
    )


ALTER TABLE Zakaznik ADD constraint zakaznik_pk PRIMARY KEY CLUSTERED (IDu)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )


CREATE TABLE zbozi 
    ( idz INTEGER NOT NULL IDENTITY NOT FOR REPLICATION , 
     Nazev VARCHAR (20) NOT NULL , 
     Kratky_popis VARCHAR (50) NOT NULL , 
     Dlouhy_popis VARCHAR (1000) , 
     Sklad INTEGER NOT NULL , 
     Cena INTEGER NOT NULL , 
     Kategorie_IDk INTEGER NOT NULL 
    )


ALTER TABLE Zbozi ADD constraint zbozi_pk PRIMARY KEY CLUSTERED (IDz)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )


ALTER TABLE Komentar
    ADD CONSTRAINT komentar_zakaznik_fk FOREIGN KEY ( zakaznik_idu )
        REFERENCES zakaznik ( idu )
ON DELETE NO ACTION 
    ON UPDATE no action 

ALTER TABLE Komentar
    ADD CONSTRAINT komentar_zbozi_fk FOREIGN KEY ( zbozi_idz )
        REFERENCES zbozi ( idz )
ON DELETE NO ACTION 
    ON UPDATE no action 

ALTER TABLE Kosik
    ADD CONSTRAINT kosik_zakaznik_fk FOREIGN KEY ( zakaznik_idu )
        REFERENCES zakaznik ( idu )
ON DELETE NO ACTION 
    ON UPDATE no action 

ALTER TABLE Kosik
    ADD CONSTRAINT kosik_zbozi_fk FOREIGN KEY ( zbozi_idz )
        REFERENCES zbozi ( idz )
ON DELETE NO ACTION 
    ON UPDATE no action 

ALTER TABLE Objednavka
    ADD CONSTRAINT objednavka_zakaznik_fk FOREIGN KEY ( zakaznik_idu )
        REFERENCES zakaznik ( idu )
ON DELETE NO ACTION 
    ON UPDATE no action 

ALTER TABLE Obrazek
    ADD CONSTRAINT obrazek_zbozi_fk FOREIGN KEY ( zbozi_idz )
        REFERENCES zbozi ( idz )
ON DELETE NO ACTION 
    ON UPDATE no action 

ALTER TABLE ObsahObjednavky
    ADD CONSTRAINT obsahobjednavky_objednavka_fk FOREIGN KEY ( objednavka_ido )
        REFERENCES objednavka ( ido )
ON DELETE NO ACTION 
    ON UPDATE no action 

ALTER TABLE ObsahObjednavky
    ADD CONSTRAINT obsahobjednavky_zbozi_fk FOREIGN KEY ( zbozi_idz )
        REFERENCES zbozi ( idz )
ON DELETE NO ACTION 
    ON UPDATE no action 


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             0
-- ALTER TABLE                             17
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
